### ISSUE TITLE
Tags and sdist

### ISSUE THREAD

**Issue by jayvdb** [SimplyKnownAsG/yamlize#4]
I was going to package this for openSUSE, but then you do not have sdist on PyPI and are missing the latest tag here on GitHub, so I cant get a versioned tarball to build from. :-(

**Comment by SimplyKnownAsG** [comment]
Hi @jayvdb, I don't understand what I'd need to do to help. Can you expand on what I should do? You could also create a pull request.

**Comment by SimplyKnownAsG** [comment]
let me know what you need, and i'll do it. for now, I'm closing

**Comment by jayvdb** [comment]
Last tag is https://github.com/SimplyKnownAsG/yamlize/releases/tag/0.6.0

Last release is https://pypi.org/project/yamlize/0.6.1/

**Comment by SimplyKnownAsG** [comment]
I added the tag, but not the source distribution. I assume the source distribution you are looking for is a .tar.gz as is created by `setup.py sdist`.

As soon as this builds and passes: https://travis-ci.org/github/SimplyKnownAsG/yamlize/jobs/747142543, I will try to push a new version 0.7.0 with source and wheel.

**Comment by SimplyKnownAsG** [comment]
I've created a new distribution for 0.7.0 which includes a wheel and source distribution but only supports Python3. I don't recall why I dropped Python2, but it is 2020!
