### ISSUE TITLE
 LICENSE not included in PyPI sdist

### ISSUE THREAD

**Issue by jayvdb** [SimplyKnownAsG/yamlize#7]
The PyPI artifacts needs to include the `LICENSE`.  Recent setuptools will include this automatically.
Otherwise a MANIFEST.in is needed.

**Comment by jayvdb** [comment]
btw, https://build.opensuse.org/package/show/home:jayvdb:py-new/python-yamlize created

**Comment by SimplyKnownAsG** [comment]
Sorry, I'm a bit naive on this. Does this mean I just need to update setuptools before building/releasing? I haven't really liked the MANIFEST thing. Any opinions of your own are welcome!

**Comment by jayvdb** [comment]
You can use a more recent setuptools, and it should do the trick, but IMO explicit (`MANIFEST.in`) is better than implicit.  If using a recent setuptools works for you, add `setup_requires=['setuptools>=..']` to avoid regressions.

**Comment by SimplyKnownAsG** [comment]
I think this is done now.
