### ISSUE TITLE
Tests failing on Python 2 due to assertRegex

### ISSUE THREAD

**Issue by jayvdb** [SimplyKnownAsG/yamlize#8]
Not sure if you want to support Python 2.
If so, the use of `assertRegex` in a few tests should be adjusted so that they are Python 2 compatible

**Comment by SimplyKnownAsG** [comment]
Do you have a need for python 2? I was planning on dropping support.

**Comment by jayvdb** [comment]
Nope.  Dropping support is reasonable IMO.

**Comment by SimplyKnownAsG** [comment]
Excellent, then we'll close this out.
